#include "Proxy.h"
#include "Export.h"


EXPORT_CLASS(GameObject)
EXPORT(GameObject, SetName)
EXPORT(GameObject, GetName)
EXPORT(GameObject, SetTranslation)
EXPORT(GameObject, GetTranslation)
EXPORT(GameObject, SetRotation)
EXPORT(GameObject, GetRotation)
EXPORT(GameObject, Subscribe)
EXPORT(GameObject, SendEvent)
EXPORT(GameObject, CreateGameObject)
EXPORT(GameObject, AddComponent)
EXPORT(GameObject, Walk)
EXPORT(GameObject, Strife)
EXPORT(GameObject, Ascend)
EXPORT(GameObject, Pitch)
EXPORT(GameObject, Yaw)
EXPORT(GameObject, Roll)
EXPORT(GameObject, Destroy)
EXPORT(GameObject, GetRef)
EXPORT(GameObject, GetObjectId)
EXPORT(GameObject, IsDestroyed)
EXPORT(GameObject, GetComponent)
GC(GameObject)
END_EXPORT()

EXPORT_CLASS(Scene)
EXPORT(Scene, CreateGameObject)
EXPORT(Scene, CreateComponent)
GC(Scene)
END_EXPORT()

EXPORT_CLASS(Level)
EXPORT(Level, GetModel)
EXPORT(Level, GetMaterial)
EXPORT(Level, GetScene)
EXPORT(Level, ListModels)
GC(Level)
END_EXPORT()

EXPORT_CLASS(Model)
GC(Model)
END_EXPORT()

EXPORT_CLASS(MeshRenderer)
EXPORT(MeshRenderer, SetModel)
EXPORT(MeshRenderer, SetMaterial)
GC(MeshRenderer)
END_EXPORT()

EXPORT_CLASS(Material)
EXPORT(Material, GetUrl)
GC(Material)
END_EXPORT()

EXPORT_CLASS(InputSystem)
EXPORT(InputSystem, GetAction)
GC(InputSystem)
END_EXPORT()

EXPORT_CLASS(PhysicsObject)
EXPORT(PhysicsObject, CreateShapeFromModel)
EXPORT(PhysicsObject, SetObjectType)
GC(PhysicsObject)
END_EXPORT()

EXPORT_CLASS(BlendingNode)
EXPORT(BlendingNode, SetParameter)
END_EXPORT()

EXPORT_CLASS(Animator)
EXPORT(Animator, GetBlendingNode)
END_EXPORT()